### ISSUE TITLE
Add Benchmarks

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#13]

**Comment by Maganpreet** [comment]
I wanna start working on this. Can anyone help me get started?

**Comment by Marusyk** [comment]
Hi @Maganpreet,

It should be used [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) package.

For examples you can look at:
 - https://github.com/jaegertracing/jaeger-client-csharp
 - https://github.com/opentk/opentk/tree/master/OpenTK.Benchmarks
 - https://github.com/yellowfeather/DbfDataReader/tree/master/test/DbfDataReader.Benchmarks
 - https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/src/Datadog.Trace.BenchmarkDotNet
 - https://github.com/JoshClose/CsvHelper/tree/master/performance/CsvHelper.Performance
 - https://github.com/DataDog/dd-trace-dotnet/tree/master/test/benchmarks/Benchmarks.Trace
 - https://github.com/AdamsLair/duality/tree/master/Benchmarks/DualityBenchmarks
 - https://github.com/Marusyk/BinaryTree

**Comment by Maganpreet** [comment]
Ok thanks!!! Will start looking into this.

**Comment by Maganpreet** [comment]
I installed BenchmarkDotNet using "nuget install BenchmarkDotNet" and it downloaded all packages and dependencies associated with it in the root is that correct? 
![grok](https://user-images.githubusercontent.com/32263581/108939189-565e0c80-761f-11eb-8a4d-0525a8346e32.PNG)

**Comment by Marusyk** [comment]
Emm, not sure. Something strange

**Comment by Maganpreet** [comment]
Yes, anyway I am looking into it. I'll let you know

**Comment by expired-ramen** [comment]
Hey i'd like to help with the project. What do you need?

**Comment by Marusyk** [comment]
yes, welcome)

**Comment by kaabus** [comment]
Can I contribute to this ??

**Comment by Marusyk** [comment]
@kaabus sure, go ahead. Thanks for your interest

**Comment by AnaOddles** [comment]
Hi! I am a beginner, can I take try to contribute to this?

**Comment by Marusyk** [comment]
Hi @AnaOddles, yes please

**Comment by MarviMcFly** [comment]
@Marusyk Hi there, are there any special requirements by adding some benchmarks? Should the benchmarks added as an additional test?

**Comment by Marusyk** [comment]
Hi @MarviMcFly
no, there are no special requirements except one - use BenchmarkDotNet package.

**Comment by obinnadtq** [comment]
Hi Please can I work on this?

**Comment by Marusyk** [comment]
hi @obinnadtq sure

**Comment by obinnadtq** [comment]
> hi @obinnadtq sure

Created a [PR](https://github.com/Marusyk/grok.net/pull/22)
