### ISSUE TITLE
Add Custom Grok Patterns Documentation

### ISSUE THREAD

**Issue by ibigpapa** [Marusyk/grok.net#15]
From the code it looks like it loads the file locally to bring in grok patterns.  It'd be great if I could provide a supplemental file with custom patterns to also include.   Or if that already exists it'd be great to see how to do so.

**Comment by Marusyk** [comment]
Hi @ibigpapa,
Totally agree with you, it would be a great feature.
Would you interested in preparing a PR for this?

**Comment by ibigpapa** [comment]
probably could just don't know when i might get to it.  Have to see how tomorrow plays out to determine how much spare time i can invest anywhere.

**Comment by DurveshKumarPal** [comment]
1.Create a directory called patterns with a file in it called extra (the file name doesn't matter, but name it meaningfully for yourself)
2.In that file, write the pattern you need as the pattern name, space, then the regexp for that pattern.
