### ISSUE TITLE
Add validation of custom grok patterns file

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#18]
### Context
The support of custom grok patterns was added in #15 

Just add the directory with name `Patterns` and a file (the file name doesn't matter) with your own patterns.

Like Patterns\grok-custom-patterns: 
```
ZIPCODE [1-9]{1}[0-9]{2}\s{0,1}[0-9]{3}
```
and use:
```csharp
Grok grok = new Grok("%{ZIPCODE:zipcode}:%{EMAILADDRESS:email}");
var grokResult = grok.Parse($"122001:Bob.Davis@microsoft.com");
```
### IndexOutOfRangeException
There is an issue when that custom file has the wrong content.
### How to reproduce
Add to the Patterns\grok-custom-patterns the following data:
```
pattern
```
### How to fix
Add some validation on load of custom grok file content. It should be pattern name, space, then the regexp for that pattern

**Comment by ManasviGoyal** [comment]
please elaborate so that i can get started

**Comment by Marusyk** [comment]
@ManasviGoyal thanks for your interest. You can start whenever you want

**Comment by ManasviGoyal** [comment]
@Marusyk how is this different from #19 ?

**Comment by Marusyk** [comment]
@ManasviGoyal this is about bug IndexOutOfRangeException and about adding some validation
#19 was about adding documentation to the README

**Comment by Marusyk** [comment]
Hi @ManasviGoyal, are you still working on that?

**Comment by ManasviGoyal** [comment]
> Hi @ManasviGoyal, are you still working on that?

I am busy with some work this month. You can can assign it someone else. No issue with me.

**Comment by MazixM** [comment]
Hi, i would like to try to fix it. Can i?

**Comment by GioMaz** [comment]
Hello, I would like to contribute to this issue as well

**Comment by Marusyk** [comment]
Hi @MazixM and @GioMaz,
Thanks for your interest. 
You need to create a Pull Request with changes. Then we can choose the best one
