### ISSUE TITLE
Add documentation of custom grok patterns

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#19]
### Context
The support of custom grok patterns was added in #15 

Just add the directory with the name `Patterns` and a file (the file name doesn't matter) with your own patterns.

Like Patterns\grok-custom-patterns: 
```
ZIPCODE [1-9]{1}[0-9]{2}\s{0,1}[0-9]{3}
```
and use:
```csharp
Grok grok = new Grok("%{ZIPCODE:zipcode}:%{EMAILADDRESS:email}");
var grokResult = grok.Parse($"122001:Bob.Davis@microsoft.com");
```

### DoD
Describe a new feature in [README](https://github.com/Marusyk/grok.net/blob/main/README.md)

**Comment by ManasviGoyal** [comment]
can you pls elaborate? would like to work in this

**Comment by Marusyk** [comment]
Hi @ManasviGoyal please go ahead

**Comment by ManasviGoyal** [comment]
Can you help me get started? @Marusyk

**Comment by Marusyk** [comment]
@ManasviGoyal here is everything you need. Other information is in README.md. What other help do you need?

**Comment by obinnadtq** [comment]
Hi, please can I try working on this as well?

**Comment by ManasviGoyal** [comment]
> Hi @ManasviGoyal please go ahead. It is yours

@Marusyk so i just have to describe this feature in the Read me file, right?

**Comment by Marusyk** [comment]
right

**Comment by ManasviGoyal** [comment]
@Marusyk pls check
