### ISSUE TITLE
[Proposal] Can we remove grok-patterns file ?

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#25]
Can we remove grok-patterns file and hardcode all values into the source code?
What do you think?

**Comment by MalcolmAnderson** [comment]
What's the value of hard coding the values over using pattern files?
My default reaction is to not hardcode anything that could change.

**Comment by Marusyk** [comment]
It's just a suggestion. We can avoid coping grok-patterns file to the bin directory on the clients
