### ISSUE TITLE
Workflow improvements

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#31]
Workflow in this repository should be both minimalistic and working example of creating your own NuGet available library. It needs some discussions what is a "good practice here". Here are some topics to discuss, even before implementing:

All with respect to versions/tags:

- take a version of the library from .csproj?
- when to tag?
- when to create a release?
- when and how to trigger publishing NuGet package?

**Comment by fasetto** [comment]
I think we should trigger the publishing when we create a release from GitHub. That is the best approach to me.
I am working on #36 Right now its triggered when we push to the main branch. But I can change that if you agree with me on this.

**Comment by Marusyk** [comment]
Please note that there is https://github.com/Marusyk/grok.net/blob/main/build.cake 
All workflows should be based on it
Use GitHub Actions only for call targets from cake script
