### ISSUE TITLE
GitHub Actions for creating release

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#32]
Add Create Release action

**Comment by Nikhil-1503** [comment]
Can I work on this?

**Comment by Marusyk** [comment]
Hi @Nikhil-1503,
sure, go-ahead

**Comment by AR10X** [comment]
Hi, Can I work on this? I would love to contribute 😄

**Comment by Marusyk** [comment]
Hi @AR10X 
This issue has already done.
You can look at others https://github.com/Marusyk/grok.net/labels/good%20first%20issue

**Comment by Marusyk** [comment]
@Nikhil-1503 
the new release should not be created after each commit to master
I reverted your changes.
This should be done manually or when changing the version

**Comment by Marusyk** [comment]
Hi @Demigodplayz 
Yes, it should be triggered when a new tag is created, I think
