### ISSUE TITLE
Add Unit Tests to improve Code Coverage

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#41]
Now it is
[![Coverage Status](https://coveralls.io/repos/github/Marusyk/grok.net/badge.svg?branch=main)](https://coveralls.io/github/Marusyk/grok.net?branch=main)</br>

Let's improve that

**Comment by marce1994** [comment]
Can I take this one?

**Comment by Marusyk** [comment]
@marce1994 sure, it is yours

**Comment by marce1994** [comment]
@Marusyk It's a little bit difficult, I don't know how to pass through the untested parts of the code :(
Untested code:
Grok.cs lines: 91 to 109, 139(untestable), 163, 209.
![image](https://user-images.githubusercontent.com/358126/137245993-f4fbde53-e3e7-408d-9372-e9751831e75f.png)

**Comment by Marusyk** [comment]
hi @marce1994 
it is ok if you cannot cover some lines. Our goal is to increase the coverage percentage, it doesn't have to be 100

**Comment by Marusyk** [comment]
Not it is 96%!

![image](https://user-images.githubusercontent.com/9221694/137973289-84a42410-5a89-4780-ac64-07132cdc7f1a.png)

**Comment by moeddami** [comment]
Code coverage went down to 65% after we added the PowerShell module. I will write unit tests for it.

**Comment by Marusyk** [comment]
Not it is
![image](https://user-images.githubusercontent.com/9221694/148838143-6afe549c-2065-4e62-88c2-d93a54ca34a5.png)

**Comment by Marusyk** [comment]
Now it is
![image](https://user-images.githubusercontent.com/9221694/149033051-a7d317a8-fd14-40ff-8364-6514048b24a3.png)

I'm going to close the issue for now :)
