### ISSUE TITLE
Using EditorConfig-Action

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#54]
Extend workflow with: https://github.com/zbeekman/EditorConfig-Action

**Comment by jatingandhimaersk** [comment]
Where is the issue mentioned?

**Comment by Marusyk** [comment]
Hi @jatingandhimaersk 
what do you mean?

**Comment by DASchechtman** [comment]
So what exactly are you asking for here?

**Comment by Marusyk** [comment]
Integrate EditorConfig-Action into workflows

**Comment by DASchechtman** [comment]
ok I see. another question. how do I build this project so I can make changes? I tried to build and ran into a lot of errors

**Comment by Marusyk** [comment]
What kind of errors? Do you mean builds.yml?

**Comment by Marusyk** [comment]
emmm...
this is not a build error.
![image](https://user-images.githubusercontent.com/9221694/176026243-f2d1f872-cda8-4acd-a79f-1c6d668061c2.png)

please take a closer look at the error message. it says that you cannot run (F5) the project because it is a class library (nuget package)

**Comment by Marusyk** [comment]
It seems you don't familiar with .NET ecosystem very well. I would recommend you to learn more about .NET, gain practical experience, and then come back to this task. Good luck

**Comment by DASchechtman** [comment]
I was able to get it running by running the test files. But thanks for the help anyway

**Comment by Marusyk** [comment]
hi @FarzamMohammadi 
sure, go-ahead

**Comment by FarzamMohammadi** [comment]
Okay here it is:
https://github.com/Marusyk/grok.net/pull/57
any feedback/suggestions?

**Comment by Marusyk** [comment]
great, could you show us screen with result?
