### ISSUE TITLE
Include symbols (PDB) for binary

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#60]
Consumers should be able to debug the code of the package if something doesn't work as expected.
Use `<DebugType>embedded</DebugType>`, include the PDbs in the package, or use a [symbol package (snupkg)](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg?WT.mc_id=DT-MVP-5003978)
PDB should use the [portable format](https://github.com/dotnet/runtime/blob/87572a799bfd37779c079faf28544e3f9a16be58/src/libraries/System.Reflection.Metadata/specs/PortablePdb-Metadata.md) to be compatible with all platforms. The file is also smaller than the Windows PDB format.

**Comment by UnfixedSun** [comment]
Hi,I would like to work on this issue .Can you please assign this issue to me.

**Comment by Marusyk** [comment]
It's yours 😉
