### ISSUE TITLE
Multiline strings

### ISSUE THREAD

**Issue by ricsiLT** [Marusyk/grok.net#66]
Hi,

Since we're essentially passing down Regex to Grok, and Regex supports multiline via RegexOptions.Singleline, could it be supported in this package? I have some logs that unfortunately have `\n`s in them and I don't want to create a new object via `.Replace()` call. As it stands now, when I try to parse such string I only get items up to newline :(

**Comment by Marusyk** [comment]
Hello, sure. Are you interested in creating a pull request for this change?

**Comment by ricsiLT** [comment]
Hmmm. Didn't consider it but - why not :D Will try and see how it goes

**Comment by ricsiLT** [comment]
PR is there, check it out :)

**Comment by ricsiLT** [comment]
@Marusyk
