### ISSUE TITLE
Add task to run unit test in build.cake script

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#7]
build.cake has already had template for  task "Run-Unit-Tests". Need to add a simple run of unit test

https://github.com/Marusyk/grok.net/blob/9383ff302afe5acd88ae0590d4ec027c44d3feb1/build.cake#L36-L41

**Comment by reshmisaji** [comment]
can i pick this up?

**Comment by Marusyk** [comment]
Yes, please

**Comment by Marusyk** [comment]
Hi @reshmisaji, any progress with it?

**Comment by Marusyk** [comment]
Great, thank you
