### ISSUE TITLE
Use a faster regular expression engine

### ISSUE THREAD

**Issue by Marusyk** [Marusyk/grok.net#71]
The Regex class in the .NET uses the .NET regular expression engine. This engine is a good general-purpose engine, but it is not the fastest. If we need the best possible performance, you can use a faster regular expression engine, such as the PCRE library.

The PCRE library is a faster regular expression engine that is available for free.

We can use the PCRE library in C# by using the PCRE.NET: https://github.com/ltrzesniewski/pcre-net library. This library provides a .NET wrapper for the PCRE library.

**Comment by Marusyk** [comment]
benchmarks before PCRE 
![image](https://github.com/Marusyk/grok.net/assets/9221694/8fca74a2-2896-4a31-972b-deef95e2177f)

**Comment by teo-tsirpanis** [comment]
I wonder, had you tried using the [Regex source generator](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators)?
